#!/bin/python

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    counter=0
    counter2=len(arr)-1
    left_arr=[]
    right_arr=[]
    for i in range(len(arr)):
        left_arr.append(arr[counter][counter])
        counter+= 1
    print(left_arr)
    counter=0
    for i in range(len(arr)):
        right_arr.append(arr[counter][counter2])
        counter+= 1
        counter2-= 1
    print(right_arr)
    return abs(sum(left_arr)-sum(right_arr))

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(raw_input().strip())

    arr = []

    for _ in xrange(n):
        arr.append(map(int, raw_input().rstrip().split()))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
