#!/bin/python

import math
import os
import random
import re
import sys

# Complete the compareTriplets function below.
def compareTriplets(a, b):
    counter=0
    counter1=0
    counter2=0
    for i in range(len(a)):
        point1=(a[i])
        point2=(b[i])
        if point1>point2:
            counter+=1
        elif point1==point2:
            counter1+=1
        else:
            counter2+=1
    print counter,counter2
    return counter,counter2

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    a = map(int, raw_input().rstrip().split())

    b = map(int, raw_input().rstrip().split())

    result = compareTriplets(a, b)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
